language: java
jdk:
  - oraclejdk8
os: 
  - windows
install: true
script: 
  - ./mvnw clean install
  - choco install jdk8
  - export PATH=$PATH:"/c/Program Files/Java/jdk1.8.0_191/bin"
  - java -version


