language: java
os: 
  - linux
#  - windows https://travis-ci.community/t/java-support-on-windows/286/6
#    install: choco install jdk8 --x64
jdk:
  - oraclejdk8
script: 
  - mvn clean package
#bash: 
#  - apt-get install oraclejdk8 



